import { Link } from "react-router-dom";
import { NeedsRun, NextStage, PageHead, Problem, QueryField, Waiting } from "../components/analysis";
import { Cyanotype, Datum, Figure, IdChip, Label, Meter, Reveal, Rule, Section } from "../components/ui";
import type { EvidenceComponentName, RankedCandidate } from "../api/types";
import { EVIDENCE_COLOR_VAR, formatScore } from "../lib/format";

/** Short forms, so the three meters in a ranking row stay on one line each
 * and the bars line up. The full names are used everywhere they fit. */
const ROW_LABEL: Record<EvidenceComponentName, string> = {
  gene_target: "Gene",
  pathway: "Pathway",
  ml: "Model",
};
import { useDiscovery, useFocusedCandidate, useRestoredRun } from "../state/DiscoveryContext";

/**
 * Stage 07. The ranked list, and the entry point for the whole analysis —
 * selecting here is what Fusion, Graph and AI Explanation follow.
 */
export function CandidatesPage() {
  const { state, run } = useRestoredRun();
  const { candidate: focused, select } = useFocusedCandidate();

  return (
    <>
      <Section>
        <PageHead
          stage="07"
          title="Candidate ranking"
          lede="Every drug that met the disease's biology, ordered by its fused repurposing score. The evidence behind each one is on the same line as the score — there is no ranking signal hidden from this view."
          art="range"
        >
          <QueryField
            onSubmit={(q) => void run(q)}
            busy={state.status === "loading"}
            initial={state.status === "success" ? state.data.disease.disease_name : ""}
            placeholder="Disease to rank candidates for"
            action="Run pipeline"
            suggestions={["asthma", "psoriasis", "type 2 diabetes mellitus"]}
          />
        </PageHead>
      </Section>

      {state.status === "loading" ? (
        <Section>
          <Waiting note={`Generating and ranking candidates for ${state.query}`} />
        </Section>
      ) : null}

      {state.status === "error" ? (
        <Section>
          <div className="py-6">
            <Problem error={state.error} onRetry={(q) => void run(q)} />
          </div>
        </Section>
      ) : null}

      {state.status === "idle" ? (
        <Section>
          <NeedsRun what="ranked candidates" />
        </Section>
      ) : null}

      {state.status === "success" ? (
        <>
          <Funnel />
          <Ranking selected={focused?.drug_id ?? null} onSelect={select} />
          <Method />
        </>
      ) : null}

      <Section>
        <NextStage from="/candidates" />
      </Section>
    </>
  );
}

/** How a universe of drugs narrowed to this list — the backend's own counts. */
function Funnel() {
  const { state } = useDiscovery();
  if (state.status !== "success") return null;
  const { candidate_summary: s, disease } = state.data;
  const universe = s.counts_by_method.universe ?? null;

  return (
    <Section tone="sunk">
      <div className="py-16">
        <Reveal>
          <div className="flex flex-wrap items-end justify-between gap-6">
            <div>
              <Label tone="ink">Candidate generation</Label>
              <h2 className="mt-4 text-[clamp(1.75rem,4vw,2.75rem)] font-semibold">
                How {disease.disease_name} narrowed the field
              </h2>
            </div>
            <IdChip>{disease.disease_id}</IdChip>
          </div>
        </Reveal>

        <Reveal delay={1}>
          <div className="mt-12 grid gap-10 border-t border-rule pt-10 sm:grid-cols-2 lg:grid-cols-4">
            {universe !== null ? <Figure value={universe} caption="Drugs in the universe" /> : null}
            <Figure value={s.candidates_discovered} caption="Generated as candidates" />
            <Figure value={s.candidates_ranked} caption="Ranked and returned" />
            <Figure value={s.n_with_ml_evidence} caption="With a model signal" />
          </div>
        </Reveal>

        <Reveal delay={2}>
          <div className="mt-12 border-t border-rule pt-8">
            <Label>Generated by route</Label>
            <div className="mt-5 grid gap-x-12 gap-y-1 sm:grid-cols-2">
              {Object.entries(s.counts_by_method)
                .filter(([k]) => k !== "universe")
                .map(([method, count]) => (
                  <Datum key={method} term={method.replace(/_/g, " ")}>
                    {count}
                  </Datum>
                ))}
            </div>
          </div>
        </Reveal>
      </div>
    </Section>
  );
}

function Ranking({ selected, onSelect }: { selected: string | null; onSelect: (id: string) => void }) {
  const { state } = useDiscovery();
  if (state.status !== "success") return null;
  const candidates = state.data.ranked.candidates;

  if (!candidates.length) {
    return (
      <Section>
        <div className="py-16">
          <p className="max-w-lg text-lg text-ink-soft">
            No candidate met the evidence requirements for this disease. That is a result, not an error — the
            pipeline does not manufacture a ranking when nothing matched.
          </p>
        </div>
      </Section>
    );
  }

  return (
    <Section>
      <Cyanotype art="column" className="absolute -right-16 top-32 w-52 opacity-[0.14]" drift />
      <div className="relative py-20">
        <Reveal>
          <div className="flex flex-wrap items-end justify-between gap-4">
            <h2 className="text-[clamp(1.75rem,4vw,2.75rem)] font-semibold">Ranked candidates</h2>
            <p className="label max-w-xs sm:text-right">Select one to carry it through fusion, graph and explanation</p>
          </div>
        </Reveal>

        <Reveal delay={1}>
          <ul className="mt-12">
            {candidates.map((c) => (
              <CandidateRow key={c.drug_id} candidate={c} selected={c.drug_id === selected} onSelect={onSelect} />
            ))}
          </ul>
        </Reveal>
      </div>
    </Section>
  );
}

function CandidateRow({
  candidate,
  selected,
  onSelect,
}: {
  candidate: RankedCandidate;
  selected: boolean;
  onSelect: (id: string) => void;
}) {
  const byName = new Map(candidate.fusion.components.map((c) => [c.name, c] as const));
  const families: EvidenceComponentName[] = ["gene_target", "pathway", "ml"];

  return (
    <li
      className="border-t transition-colors"
      style={{ borderColor: selected ? "var(--color-blue)" : "var(--color-rule)" }}
    >
      <button
        type="button"
        onClick={() => onSelect(candidate.drug_id)}
        aria-pressed={selected}
        className="group grid w-full items-center gap-x-8 gap-y-4 py-6 text-left md:grid-cols-[3rem_1fr_1.3fr_7rem]"
      >
        <span className="tabular label">{String(candidate.rank).padStart(2, "0")}</span>

        <span>
          <span
            className="block font-display text-[clamp(1.25rem,2.6vw,1.75rem)] font-semibold tracking-tight transition-colors group-hover:text-blue"
            style={selected ? { color: "var(--color-blue)" } : undefined}
          >
            {candidate.drug_name}
          </span>
          <span className="label mt-1 block">{candidate.generation_methods.join(" + ")}</span>
        </span>

        <span className="grid gap-2">
          {families.map((name) => {
            const component = byName.get(name);
            return (
              <span key={name} className="grid items-center gap-3 sm:grid-cols-[5.5rem_1fr_2.5rem]">
                <span className="label whitespace-nowrap">{ROW_LABEL[name]}</span>
                <Meter value={component?.value ?? 0} color={EVIDENCE_COLOR_VAR[name]} height={4} />
                <span className="tabular text-right text-xs text-ink-soft">
                  {component?.available && component.value !== null ? component.value.toFixed(2) : "n/a"}
                </span>
              </span>
            );
          })}
        </span>

        <span className="text-left md:text-right">
          <span className="tabular block font-display text-[clamp(1.5rem,3vw,2rem)] font-semibold leading-none tracking-tight text-blue">
            {formatScore(candidate.repurposing_score)}
          </span>
          <span className="label mt-1.5 block">/ 100</span>
        </span>
      </button>

      {selected ? <SelectedDetail candidate={candidate} /> : null}
    </li>
  );
}

function SelectedDetail({ candidate }: { candidate: RankedCandidate }) {
  const links = [
    { to: "/fusion", label: "How this score was built" },
    { to: "/graph", label: "Follow it through the graph" },
    { to: "/explanation", label: "Read the AI explanation" },
    { to: "/prediction", label: "Inspect the model signal" },
  ];

  return (
    <div className="grid gap-10 pb-10 md:grid-cols-[1.2fr_1fr]">
      <div>
        <Label tone="ink">Matched identifiers</Label>
        <div className="mt-4 space-y-4">
          <IdGroup term="Disease genes" ids={candidate.matched_disease_gene_ids} />
          <IdGroup term="HGNC" ids={candidate.matched_gene_hgnc_ids} />
          <IdGroup term="Drug targets" ids={candidate.matched_drug_target_ids} />
          <IdGroup term="Reactome pathways" ids={candidate.matched_pathway_reactome_ids} />
        </div>
      </div>

      <div>
        <Label tone="ink">Carry this candidate forward</Label>
        <ul className="mt-4">
          {links.map((l) => (
            <li key={l.to}>
              <Link
                to={l.to}
                className="group flex items-center justify-between border-t border-rule py-3 text-[0.9375rem] transition-colors hover:border-blue hover:text-blue"
              >
                {l.label}
                <span aria-hidden className="transition-transform group-hover:translate-x-1">
                  →
                </span>
              </Link>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}

function IdGroup({ term, ids }: { term: string; ids: string[] }) {
  if (!ids.length) return null;
  return (
    <div>
      <p className="label">{term}</p>
      <div className="mt-2 flex flex-wrap gap-1.5">
        {ids.map((id) => (
          <IdChip key={id}>{id}</IdChip>
        ))}
      </div>
    </div>
  );
}

function Method() {
  const { state } = useDiscovery();
  if (state.status !== "success") return null;
  const p = state.data.ranked.provenance;

  return (
    <Section tone="navy" railed={false}>
      <div className="relative py-20">
        <Reveal>
          <Label tone="navy">Ranking method</Label>
          <h3 className="mt-4 max-w-2xl text-[clamp(1.5rem,3.4vw,2.5rem)] font-semibold text-navy-text">
            {p.ranking_signal}
          </h3>
        </Reveal>
        <Reveal delay={1}>
          <dl className="mt-10 grid gap-x-14 md:grid-cols-2">
            <Datum tone="navy" term="Ranking version">
              {p.ranking_version}
            </Datum>
            <Datum tone="navy" term="Tie breaker">
              {p.tie_breaker}
            </Datum>
            <Datum tone="navy" term="Scores recalculated here">
              {p.scores_recalculated ? "yes" : "no"}
            </Datum>
            <Datum tone="navy" term="Biology recalculated here">
              {p.biology_recalculated ? "yes" : "no"}
            </Datum>
            <Datum tone="navy" term="Input candidates">
              {p.n_input}
            </Datum>
            <Datum tone="navy" term="Ranked">
              {p.n_ranked}
            </Datum>
          </dl>
        </Reveal>
        <Reveal delay={2}>
          <div className="mt-10">
            <Rule tone="navy" dotted />
            <p className="mt-6 max-w-3xl leading-relaxed text-navy-muted">{p.interpretation}</p>
            <p className="mt-3 max-w-3xl text-sm leading-relaxed text-navy-faint">{p.disclaimer}</p>
          </div>
        </Reveal>
      </div>
    </Section>
  );
}
